// This file is auto-generated by Payload's withPayload plugin during `next dev` / `next build`.
// Do not edit manually — it maps custom components to their import paths for the admin panel.
// If you need to add custom admin components, register them in payload.config.ts and let Payload regenerate this.
export const importMap = {};
